# Generated by Django 3.1.5 on 2021-01-15 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('user', '0001_initial'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('ad_text', models.TextField(verbose_name='Текст объявления')),
                ('salary', models.IntegerField(default='0', verbose_name='Заработная плата')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='организация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='пользователь')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.work', verbose_name='работа')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'db_table': 'ad',
                'ordering': ['organization'],
            },
        ),
    ]
